Test/Controllers/AuthorController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Test.Data.Interfaces;
using Test.Data.Models;

namespace Test.Controllers
{
    public class AuthorController : Controller
    {
        private readonly IAllAuthor allauthors;

        public AuthorController(IAllAuthor allauthors)
        {
            this.allauthors = allauthors;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(Author author)
        {
            if (ModelState.IsValid)
            {
                allauthors.createAuthor(author);
                return RedirectToAction("Complete");
            }

            return View(author);
        }

        public IActionResult Complete()
        {
            ViewBag.Message = "Author added";
            return View();
        }
        
    }
}

Test/Controllers/BookController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using Test.Data.Interfaces;
using Test.Data.Models;
using Test.ViewModels;

namespace Test.Controllers
{
    public class BookController : Controller
    {
        private readonly IAllBooks allBooks;
        private readonly IAllPublisher allPublisher;
        public BookController(IAllBooks allBooks, IAllPublisher allPublisher)
        {
            this.allBooks = allBooks;
            this.allPublisher = allPublisher;
        }
        
        public IActionResult Index()
        {
            var publishers = allPublisher.getAllPublisher.ToList();
            SelectList list = new SelectList(publishers, "id", "name");
            ViewBag.allPublisher = list;
            return View();
        }

        [HttpPost]
        public IActionResult Index(Book book)
        {
            if (ModelState.IsValid)
            {
                allBooks.createBook(book);
                return RedirectToAction("Complete");
            }

            return View(book);
        }

        public IActionResult Complete()
        {
            ViewBag.Message = "Book added";
            return View();
        }
    }
}

Test/Controllers/BookToAuthorController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Test.Data.Interfaces;
using Test.Data.Models;
using Test.ViewModels;

namespace Test.Controllers
{
    public class BookToAuthorController : Controller
    {
        private readonly IBookToAuthor iBookToAuthor;
        private readonly IAllAuthor allAuthor;
        private readonly IAllBooks allBooks;
        private readonly IAllPublisher allPublisher;

        public BookToAuthorController(IBookToAuthor ibookToAuthor, IAllAuthor allAuthor, IAllBooks allBooks, IAllPublisher allPublisher)
        {
            this.iBookToAuthor = ibookToAuthor;
            this.allBooks = allBooks;
            this.allAuthor = allAuthor;
            this.allPublisher = allPublisher;
        }

        public IActionResult Index()
        {
            var authors = allAuthor.getAllAuthor.ToList();
            SelectList list = new SelectList(authors, "id", "name");
            ViewBag.allAuthor = list;

            var books = allBooks.getAllBook.ToList();
            SelectList listBooks = new SelectList(books, "id", "name");
            ViewBag.allBook = listBooks;
            return View();
        }

        [HttpPost]
        public IActionResult Index(BookToAuthor bookToAuthor)
        {
            if (ModelState.IsValid)
            {
                iBookToAuthor.create(bookToAuthor);
                return RedirectToAction("Complete");
            }

            return View(bookToAuthor);
        }
        [HttpGet]
        public IActionResult ShowTable()
        {
            List<BookToAuthor> bookToAuthors = iBookToAuthor.getData().ToList();
            BookToAuthorViewModel viewModel = new BookToAuthorViewModel();
            viewModel.allBookToAuthor = bookToAuthors;
            return View(viewModel);
        }
        [HttpPost]
        public IActionResult ShowTable(BookToAuthorViewModel bookViewModel)
        {
            if (bookViewModel.selectedValue == 1)
            {
                bookViewModel.allBookToAuthor = iBookToAuthor.getDataByNameCondition(bookViewModel.searchValue);
            }else if(bookViewModel.selectedValue == 2)
            {
                bookViewModel.allBookToAuthor = iBookToAuthor.getDataByPublisherCondition(bookViewModel.searchValue);
            }else if (bookViewModel.selectedValue == 3)
            {
                bookViewModel.allBookToAuthor = iBookToAuthor.getDataByAuthorCondition(bookViewModel.searchValue);
            }
            return View(bookViewModel);
        }


        public IActionResult Complete()
        {
            ViewBag.Message = "BookToAuthor added";
            return View();
        }
    }
}

Test/Controllers/PublisherController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Test.Data;
using Test.Data.Interfaces;
using Test.Data.Models;

namespace Test.Controllers
{
    public class PublisherController : Controller
    {
        private readonly IAllPublisher publishers;

        public PublisherController(IAllPublisher publishers)
        {
            this.publishers = publishers;
        }
        [HttpGet]
        [Route("Publisher/Index")]
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(Publisher publisher)
        {
            if (ModelState.IsValid)
            {
                publishers.createPublisher(publisher);
                return RedirectToAction("Complete");
            }
            return View(publisher);
        }

        public IActionResult Complete()
        {
            ViewBag.Message = "Издательство добавлено";
            return View();
        }
    }
}

Test/Views/Shared/AllCars.cshtml
@model Car

<div class="col-lg-4">
    <img class="img-thumbnail" src="@Model.img" alt="@Model.img" />
    <h2>@Model.name</h2>
    <p>@Model.shortDesc</p>
    <p>Цена: @Model.price.ToString("c")</p>
    <p><a class="btn btn-warning" href="#">Подробнее</a></p>
</div>

Test/Views/Shared/Info.cshtml
@model BookToAuthor

<tr>
    <td>@Model.book.name</td>
    <td>@Model.book.description</td>
    <td>@Model.book.publisher.name</td>
    <td>@Model.book.price</td>
    <td>@Model.book.publishedAt</td>
    <td>@Model.author.name</td>
</tr>

Test/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/bootstrap.min.css" type="text/css" rel="stylesheet"/>
    <link href="~/css//style.css" type="text/css" rel="stylesheet"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <a class="navbar-brand" asp-controller="BookToAuthor" asp-action="ShowTable">Домой</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Author" asp-action="Index">Добавить автора <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Publisher" asp-action="Index">Добавить издателя</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Book" asp-action="Index">Добавить книгу</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="BookToAuthor" asp-action="Index">Добавить книгу и автора</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="container mt-5">
        @RenderBody()
    </div>
    <footer class="container">
        <p class="float-right"><a href="#">Back to top</a></p>
        <p>© 2017-2020 Company, Inc. · <a href="#">Privacy</a> · <a href="#">Terms</a></p>
    </footer>
    <script src="~/js/bootstrap.min.js"></script>
</body>
</html>